### ISSUE TITLE
Prohibited term: blacklist

### ISSUE THREAD

**Issue by cdmauney** [IBM-Bluemix-Docs/BlockStorage#6]
Do not use. Use the term "blocklist" instead.

**Comment by vickmuir** [comment]
I can't replace the word 'blacklist' in the code blocks as it is part of the multipath.config file's syntax. This code is not owned or managed by IBM. The customers need to know how to update the configuration file to successfully establish and maintain a multipath connection to the Storage, which is why the syntax example exist.

https://linux.die.net/man/5/multipath.conf
https://www.systutorials.com/docs/linux/man/5-multipath.conf/
https://manpages.ubuntu.com/manpages/artful/man5/multipath.conf.5.html
http://manpages.org/multipathconf/5

**Comment by cdmauney** [comment]
@vickmuir Reopening based on recent guidance from corporate regarding third-party usage:

When you must refer to prohibited terms because they occur in a product from another company, make it clear that these terms are not from IBM. Use the verbs "block" and "allow" to refer to the action of adding items to another company's "blacklist" or "whitelist".

**Comment by vickmuir** [comment]
The offending words are in code blocks and as such completely separate from the rest of the text.
